#!/usr/bin/env bash

#You should know your CloudFrontId
# 1-Give permission for handle CloudFront to your AWS user
# 2-Look for ID of desired CloudFront distribuition -> aws cloudfront list-distributions

export AWS_ACCESS_KEY_ID=xxxxxxxxxxx
export AWS_SECRET_ACCESS_KEY=xxxxxxxxx
export AWS_DEFAULT_REGION=eu-west-1

echo "Removing all files on bucket"
aws s3 rm s3://${BUCKET} --recursive

echo "Attempting to upload site .."
echo "Command:  aws s3  sync $SOURCE_DIR s3://$BUCKET/"
aws s3  sync ${SOURCE_DIR} s3://${BUCKET}/
echo "S3 Upload complete"

echo "Invalidating cloudfrond distribution to get fresh cache"
aws cloudfront create-invalidation --distribution-id=S11A16G5KZMEQD --paths / --profile=myawsprofile

echo "Deployment complete"  
